name              'dna-osx-apps'
maintainer        'DNA Designed Communications Limited'
maintainer_email  'dev@dna.co.nz'
license           'MIT'
description       'DNA OSX Applications'
long_description  'Sets up an OSX machine at DNA'
version           '0.1.0'
supports          'mac_os_x'

depends           'pivotal_workstation'
depends           'sprout-osx-settings'
depends           'sprout-osx-apps'
