include_recipe "sprout-osx-apps::skype"
include_recipe "pivotal_workstation::shiftit"
include_recipe "sprout-osx-apps::firefox"
include_recipe "sprout-osx-apps::dropbox"
include_recipe "sprout-osx-apps::chrome"
include_recipe "sprout-osx-apps::sequelpro"
include_recipe "sprout-osx-apps::android_sdk"
include_recipe "sprout-osx-apps::chrome_canary"
include_recipe "dna-osx-apps::keepassx"
# include_recipe "sprout-osx-apps::charles_proxy"
# include_recipe "dna-osx-apps::imageoptim"
include_recipe "sprout-osx-apps::tower"
include_recipe "sprout-osx-apps::viscosity"
include_recipe "sprout-osx-apps::1password"
include_recipe "sprout-osx-apps::evernote"
include_recipe "sprout-osx-apps::vlc"
